locations:
    Bauhof/Klaeranlage:
        database: client_4_enceladus
        devices:
            Fronius Solar Inverter 1:
                thingId: 9a31ba36-cb1e-4c45-8c00-70c0e3ef5176
                measurements:
                    Erzeugung:
                        typeId: 788accbc-b86e-471b-b37f-14c9c6411526
                        unit: Watt
            Fronius Solar Inverter 2:
                thingId: f71110e2-823f-421f-a335-803c1ba3184c
                measurements:
                    Erzeugung:
                        typeId: 788accbc-b86e-471b-b37f-14c9c6411526
                        unit: Watt
            Fronius Smart Meter:
                thingId: 1614a47d-5704-4071-b63c-2019ff04d74b
                measurements:
                    Netzbezug:
                        typeId: e5056ea1-88a2-410b-9c5e-6322aca4cb17
                        unit: Watt
            iDM Waermepumpe:
                thingId: c91cd1f2-13f3-45d5-8793-b011b088b6c9
                measurements:
                    ein-/ausgeschalten:
                        typeId: 33c27167-8e24-4cc5-943c-d17cd03e0f68
                        unit: Wahrheitswert
                    Raumtemperatur:
                        typeId: f0f596bf-7e45-43ea-b3d4-767b82dd422a
                        unit: Celsius
                    Wassertemperatur:
                        typeId: fcf8e97f-a672-407f-94ae-30df15b310f4
                        unit: Celsius
                    Aussenlufttemperatur:
                        typeId: 9f3462c2-7c42-4eeb-afc4-092e1e41a25d
                        unit: Celsius
                    Relative Luftfeuchte:
                        typeId: 109b4189-491a-4498-8470-b52b1b434c71
                        unit: Prozent
                    Ziel Raumtemperatur:
                        typeId: efae7493-68c3-4cb9-853c-81011bdf09ca
                        unit: Celsius
                    Ziel Wassertemperatur:
                        typeId: 746244d6-dd37-4af8-b2ae-a7d8463e51e2
                        unit: Celsius
                    Stromverbrauch:
                        typeId: b98fb325-100d-4eae-bf8d-97e8f7e1eb00
                        unit: Watt
                    Modus:
                        typeId: e539366b-44da-4119-b11b-497bcdb1f522
                        unit: Text


